DASHBOARD_PASSWORD = "123123"
POCKETBASE_URL = "http://127.0.0.1:8090"
POCKETBASE_TOKEN= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTc1MDUxOTU2NSwiaWQiOiI2djFsanUwMmJkN2hqeWoiLCJyZWZyZXNoYWJsZSI6dHJ1ZSwidHlwZSI6ImF1dGgifQ.YOR2YbooLZExJq5ymFXJwQkDyNnZQFel99TFg2O66BQ"
POCKETBASE_COLLECTION = "matched_orders"